platform: linux

image_resource:
  type: docker-image
  source:
    repository: ruby
    tag: 2.4.1

#image_resource:
#  type: docker-image
#  source: {repository: busybox}

inputs:
- name: flight-school

run:
  path: ./flight-school/ci/test.sh
